tags:
  - continuous
  - cdep
  - dep
  - deployment

steps:
- name: 'python:3.9'
  id: "check tests"
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        pip3 install -r requirements.txt
        # Run your Python script
        python -m src.main
 
options:
  logging: CLOUD_LOGGING_ONLY