tags:
  - continuous
  - ci
  - int
  - integration
steps:
- name: 'python:3.9'
  id: "check tests"
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        pip install -r requirements.txt
        # Run your Python test
        pytest

options:
  logging: CLOUD_LOGGING_ONLY